config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations' }

  get 'home/index'

  resources :affiliates
  post 'affiliates/:id/checkin', to: 'affiliates#create_checkin'
  get 'affiliates/:id/checkin', to: 'affiliates#new_checkin'
  get 'affiliates/:id/checkins', to: 'affiliates#index_checkins'

  root 'home#index'

end

app/models/affiliate.rb
require 'set'

include Geocoder::Model::Mongoid

#
#
#
class Affiliate
  include Mongoid::Document
  field :name, type: String
  field :address1, type: String
  field :address2, type: String
  field :city, type: String
  field :state, type: String
  field :zipcode, type: Integer
  field :coordinates, type: Array
  field :default_img_path, type: String
  field :image_paths, type: Array
  field :is_featured, type: Boolean
  field :url_value, type: String

  attr_accessor :distance_from_search
  attr_accessor :avg_rating

  validates :name, presence: true, length: { in: 2..40 }
  after_validation :make_url_value

  validates :address1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode,
            presence: true,
            format: { with: /\A\d{5}-\d{4}|\A\d{5}\z/,
                      message: 'should be 12345 or 12345-1234' }

  has_many :subscriptions
  has_many :checkins
  has_many :reviews
  has_many :users

  geocoded_by :address

  after_validation :geocode, if: (lambda do |obj|
    obj.coordinates.nil? ||
      (obj.coordinates.present? && obj.coordinates_changed?)
  end)

  # accepts_nested_attributes_for :subscription

  #
  # Static method - used to find all affiliates near the given coordinates
  #
  def self.search(coordinates)
    Affiliate.geo_near(coordinates)
  end

  #
  # Used to retrieve the geocoding compliant address string
  #
  def address
    a = "#{address1}"
    a = "#{a} #{address2}" if address2?
    a = "#{a}, #{city}, #{state} #{zipcode}"
    a
  end

  #
  # Retrieve the average review rating for this affiliate
  #
  def avg_review
    # note - inject applies a binary operation on all elements and sets the
    # initial value to what you pass into inject
    reviews.count == 0 ? 0 : Float(reviews.inject(0) do |total, r|
      total + r.num_stars
    end) / Float(reviews.count)
  end

  #
  # Returns a list of characteristics as a comma-separated string
  #
  def characteristics
    chars = Set.new

    reviews.each do |review|
      chars.merge(review.characteristics)
    end

    chars.to_a.join(', ')
  end

  #
  # Sets the distance in miles from this affiliate to the coordinates passed
  # in.  This is a helper method essentially to be able to print out on the
  # search results and affiliate page the distance from where the user is
  # located, or searched near.
  #
  def set_distance_from_search(coordinates)
    self.distance_from_search = distance_to(coordinates).round(2)
  end

  protected

  #
  # Creates the url name to replace the id on the show route
  #
  def make_url_value
    self.url_value = name.gsub(/\s+/, '') unless name.nil?
  end
end

app/controllers/affiliates_controller.rb
#
# Controller managing Affiliates display, search, and listing.
#
class AffiliatesController < ApplicationController
  before_action :require_authenticated, only: [:new, :create, :edit, :update,
                                               :destroy, :create_checkin,
                                               :index_checkins]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy,
                                       :index_checkins]
  before_action :set_affiliate, only: [:show, :edit, :update, :destroy,
                                       :new_checkin, :index_checkins]

  #
  # GET /affiliates
  # GET /affiliates.json
  #
  def index
    lat = params['lat']
    lon = params['lon']

    search_location = params['search_location']

    if !search_location.nil? && !search_location.blank?
      # TODO: perform a search based on address and not lat long
    elsif valid_lat_lon(lat, lon)
      @affiliates = affiliates_with_distance_from_search(lat, lon)
      # else
      # TODO: we have a problem here...
    end

    @back_button_text = @affiliates.nil? ? 'Back' : 'Home'
    @page_text = 'Find RXN Gym'

    # respond_to do |format|
    #   format.html { redirect_to '/affiliates/search',
    #                 notice: 'Search functioned.' }
    #   format.json { render :show, status: :ok, location: @affiliate }
    # end
  end

  def valid_lat_lon(lat, lon)
    !lat.nil? && !lon.nil?
  end

  #
  #
  #
  def affiliates_with_distance_from_search(lat, lon)
    # IMPORTANT
    # for some reason the API was built to take lon/lat vs lat/lon
    Affiliate.includes(:reviews).search([Float(lon), Float(lat)]).map do |a|
      a.set_distance_from_search([lat, lon])
      a
    end
  end

  #
  # GET /affiliates/<affiliate_url_value>
  # GET /affiliates/<affiliate_url_value>.json
  #
  def show
    @page_text = @affiliate.name
  end

  #
  # GET /affiliates/new
  #
  def new
    @affiliate = Affiliate.new
    # @affiliate.build_subscription
  end

  #
  # GET /affiliates/1/edit
  #
  def edit
  end

  #
  # POST /affiliates
  # POST /affiliates.json
  #
  def create
    @affiliate = Affiliate.new(affiliate_params)

    respond_to do |format|
      if @affiliate.save
        format.html { redirect_to action: :show, id: @affiliate.url_value }
        format.json { render :show, status: :created, location: @affiliate }
      else
        format.html { render :new }
        format.json do
          render json: @affiliate.errors, status: :unprocessable_entity
        end
      end
    end
  end

  #
  # PATCH/PUT /affiliates/<affiliate_url_value>
  # PATCH/PUT /affiliates/<affiliate_url_value>.json
  #
  def update
    respond_to do |format|
      if @affiliate.update(affiliate_params)
        format.html { redirect_to action: :show, id: @affiliate.url_value }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit }
        format.json do
          render json: @affiliate.errors, status: :unprocessable_entity
        end
      end
    end
  end

  #
  # DELETE /affiliates/<affiliate_url_value>
  # DELETE /affiliates/<affiliate_url_value>.json
  #
  def destroy
    @affiliate.destroy unless @affiliate.nil?

    respond_to do |format|
      format.html { redirect_to affiliates_url }
      format.json { head :no_content }
    end
  end

  #
  #
  #
  def new_checkin
    @checkin = Checkin.new
    @affiliates = Affiliate.all
    #     @checkin.when = DateTime.now
    #     @checkin.user = current_user
  end

  #
  #
  #
  def create_checkin
    affiliate = Affiliate.where(url_value: params[:id]).first

    @checkin = Checkin.new(affiliate: affiliate, when: DateTime.now,
                           user: current_user)

    # @checkin.affiliate = affiliate
    # @checkin.when = DateTime.now
    # @checkin.user = current_user

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to action: :show, id: affiliate.url_value }
        # format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :show, location: affiliate }
        # format.json { render json: @checkin.errors,
        #              status: :unprocessable_entity }
      end
    end
  end

  #
  #
  #
  def index_checkins
    @checkins = Checkin.where(affiliate: @affiliate)
  end

  private

  #
  # Sets the affiliate based on the id parameter that was passed via the URL
  #
  def set_affiliate
    value = params[:id]
    @affiliate = Affiliate.where(url_value: value).first
  end

  #
  # Never trust parameters from the scary internet, only allow the white list
  # through.
  #
  def affiliate_params
    params.require(:affiliate).permit(
      :name, :address1, :address2, :city, :state, :zipcode, :default_img_path,
      :is_featured, subscription_attributes: [
        :plan, :cost, :joined_date, billing_info_attributes: [
          :card_company, :card_type, :card_number, :card_exp_month,
          :card_exp_year]])
  end
end

app/helpers/affiliates_helper.rb
#
#
#
module AffiliatesHelper
end

app/views/affiliates/_checkin_form.html.erb
<%= form_for(@affiliate) do |f| %>

  <div>
    <%#= f.label :affiliate, "Affiliate:", for: "affiliate", id: "affiliate-label", :class "" %>
    <%#= f.select :affiliate, options_from_collection_for_select(@affiliates, "id", "name"), {},
      id: "address1", class: "" %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affiliates/_form.html.erb
<%= form_for(@affiliate) do |f| %>

  <div>
    <%= f.label :name, 'Name:', for: 'affiliate-name', id: 'name-label', class: '' %>
    <%= f.text_field :name, id: 'affiliate-name', class: '' %>
  </div>

  <div>
    <%= f.label :address1, 'Address 1:', for: 'address1', id: 'address1-label', class: '' %>
    <%= f.text_field :address1, id: 'address1', class: '' %>
  </div>
  <div>
    <%= f.label :address2, 'Address 2:', for: 'address2', id: 'address2-label', class: '' %>
    <%= f.text_field :address2, id: 'address2', class: '' %>
  </div>
  <div>
    <%= f.label :city, 'City:', for: 'city', id: 'city-label', class: '' %>
    <%= f.text_field :city, id: 'city', class: '' %>
  </div>
  <div>
    <%= f.label :state, 'State:', for: 'state', id: 'state-label', class: '' %>
    <%= f.text_field :state, id: 'state', class: '' %>
  </div>
  <div>
    <%= f.label :zipcode, 'Zipcode:', for: 'zipcode', id: 'zipcode-label', class: '' %>
    <%= f.text_field :zipcode, id: 'zipcode', class: '' %>
  </div>

  <div class='actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/affiliates/_search_result.html.erb
<div id="photo">
  <% if affiliate.default_img_path %>
     <img src="<%= affiliate.default_img_path %>">
  <% else %>

  <% end %>
</div>

<div id="info">
  <div id="info-row-1">
    <% if affiliate.is_featured? %>
      <!-- <span id="featured-badge">FEATURED</span> -->
      <img id="featured-badge" src="assets/featured.png"></img>
    <% end %>
    <span id="name"><%= affiliate.name %></span>
  </div>

  <div id="info-row-2">
    <input id="rating-stars" class="rating" data-size="xs" data-show-caption="false" data-show-clear="false" data-readonly="true" value="<%= affiliate.avg_review %>">

    </input>
    <div id="review-count">
      <span><%= affiliate.reviews.count %> Reviews</span>
    </div>
  </div>

  <div id="info-row-3">
    <span id="address"><%= affiliate.address %></span>
  </div>

  <div id="info-row-4">
    <span id="characteristics"><%= affiliate.characteristics %></span>
  </div>

  <div id="info-row-5">
    <div id="distance-to">
      <span><%= affiliate.distance_from_search %> mi.</span>
    </div>
  </div>
</div>

app/views/affiliates/edit.html.erb
<h1>Editing Affiliate</h1>

<%= render 'form' %>

<%= link_to 'Show', @affiliate %> |
<%= link_to 'Back', affiliates_path %>

app/views/affiliates/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<% content_for :index do %>
  <%= stylesheet_link_tag 'search_results', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'star-rating.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'search_results', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'star-rating.min', 'data-turbolinks-track' => true %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <%= form_tag(affiliates_path, method: 'get') do %>
        <%= hidden_field_tag :lat, value: '' %>
        <%= hidden_field_tag :lon, value: '' %>
        <div class="input-group">
          <%= text_field_tag(:search_location, nil, placeholder: 'Type an Address, City, or State',
            class: 'form-control') %>
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit" name="commit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12">
      <% unless @affiliates.nil? %>
        <table id="results-table" class="table table-striped">
          <% @affiliates.each_with_index do |affiliate, index| %>
            <tr id="search-result-<%= index %>" class="clickable-row" data-href="affiliates/<%= affiliate.url_value %>">
              <td>
                <%= render partial: "search_result", locals: { index: index, affiliate: affiliate } %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
  </div>
</div>



<%#= link_to 'New Affiliate', new_affiliate_path %>

app/views/affiliates/new.html.erb
<h1>New Affiliate</h1>

<%= render 'form' %>

<%= link_to 'Back', affiliates_path %>

app/views/affiliates/new_checkin.html.erb
<h1>New Checkin</h1>

<%= render 'checkin_form' %>

<%#= link_to 'Back', checkins_path %>

app/views/affiliates/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<% content_for :show do %>
  <%= stylesheet_link_tag 'slick.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'slick-theme.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'star-rating.min', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'slick.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'affiliates.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'star-rating.min', 'data-turbolinks-track' => true %>
<% end %>

<div class="container-fluid">
  <div id="gym-info" class="row">
    <div class="col-sm-12 col-md-12">
      <input id="rating-stars" class="rating" data-size="xs" data-show-caption="false" data-show-clear="false"
             data-readonly="true" value="<%= @affiliate.avg_review %>">

      <div id="review-count">
        <span><%= @affiliate.reviews.count %> Reviews</span>
      </div>
    </div>
  </div>


  <div id="gym-actions" class="row">
    <div class="col-sm-12 col-md-12">
    </div>
  </div>


  <div class="row">
    <div class="col-sm-12 col-md-12">
      <span><%= @affiliate.address %></span>
    </div>
  </div>


  <div id="carousel-row" class="row">
    <div class="col-sm-12 col-md-12">
      <div id="image-carousel" class="">
        <% unless @affiliate.image_paths.nil? %>
          <% @affiliate.image_paths.each_with_index do |path, index| %>
          <div class="">
            <div class="image">
              <img src="<%= path %>" alt="">
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


  <input id="show-qr-btn" type="button" class="btn-lg btn btn-primary" value="Show QR Code"/>



</div>


<%#= link_to 'Edit', edit_affiliate_path(@affiliate) %>
<%#= link_to 'Back', affiliates_path %>



<!--<tr>-->
<!--<td></td>-->
<!--<td><%#= affiliate.distance_to([39.61671339, -104.8946896]) %></td>-->
<!--<td><%#= link_to 'Show', affiliate %></td>-->
<!--<td><%#= link_to 'Edit', edit_affiliate_path(affiliate) %></td>-->
<!--<td><%#= link_to 'Destroy', affiliate, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--</tr>-->